baseURL = "https://zhijiblog.github.com/"
languageCode = "en-us"
title = "知几小博客"
theme = "diary"

[[menu.main]]
url = "/NLP"
name = "NLP"
weight = 1

[[menu.main]]
url = "/对话系统"
name = "对话系统"
weight = 2

[[menu.main]]
url = "/posts"
name = "Archive"
weight = 4